### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by RegisHubelia** [simylein/fluxify#2]
Just wanted to say that this project is really promising.  I like the lightweight mindset and ease of customization.  Good work.

It might be a good idea to open discussions in the repo?  I have a few things I would like to add in a discussion rather than issues - and make sure that whatever I do on top of the project stays aligned with the mindset, so features can be merged instead of keeping a separate repo.

Also, I saw in the last few days that the repo was forced-pushed with "initial commit" removing all history.  Is this going to be the last force-push so we can keep track of the changes?

Again, really enjoy using this project.  It's lean, mean, easy to use, and powerful.  Keep it up!

Kind Regards.

**Comment by simylein** [comment]
Thank you for your lovely words. I  activated discussions for the repository. I will of course stop with my shenanigan force pushing.
